POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"teste2",
    "email":"teste2@teste.com.br",
    "password":"12345678"
}
###
 
POST http://localhost:3003/post 
Content-Type: application/json


